name: Backend CI

on:
  push:
    branches: [ main, develop ]
    paths: [ 'backend/**' ]
  pull_request:
    branches: [ main, develop ]
    paths: [ 'backend/**' ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ping: 1})'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
        
    - name: Install dependencies
      run: npm ci
      working-directory: backend
      
    - name: Run linter
      run: npm run lint
      working-directory: backend
      
    - name: Run tests
      run: npm test
      working-directory: backend
      env:
        MONGO_URI: mongodb://localhost:27017/agro_c_test
        JWT_SECRET: test_secret_key
        NODE_ENV: test
        
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: backend
        push: false
        tags: agro-c-backend:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
