name: ML Service CI

on:
  push:
    branches: [ main, develop ]
    paths: [ 'ml_service/**' ]
  pull_request:
    branches: [ main, develop ]
    paths: [ 'ml_service/**' ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: ml_service/requirements.txt
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ml_service/requirements.txt
        pip install pytest pytest-asyncio httpx
        
    - name: Run tests
      run: |
        cd ml_service
        python -m pytest tests/ -v --cov=app --cov-report=xml
        
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ml_service/coverage.xml
        flags: ml-service
        name: ml-service-coverage
        
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: ml_service
        push: false
        tags: agro-c-ml-service:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
